### ISSUE TITLE
Support for esp-idf http server

### ISSUE THREAD

**Issue by dorianim** [BCsabaEngine/svelteesp32#11]
Hey there,

I really like this project! It would be great if it supported the [esp-idf built in http server](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/protocols/esp_http_server.html). Like that, it would work with plain esp-idf without any additional libraries.

**Comment by BCsabaEngine** [comment]
Thank you! I did not planned, yet. But it is a simple code generator, so I try to solve it about your link. I will create a small idf app with platformIO to test result. And I need your oppinion and test :)

**Comment by dorianim** [comment]
Thanks! I'll test it as soon as it's available :)
