### ISSUE TITLE
Question : how to set up an environment?

### ISSUE THREAD

**Issue by playmiel** [BCsabaEngine/svelteesp32#6]
I'd like to know how to configure your svelte environment because I can't export my site with the command  `npx svelteesp32 -e psychic -s C: \Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\svelte_esp_web\build -o C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\src\svelteesp32. h --etag`

**Comment by BCsabaEngine** [comment]
I think there is a faulty space after -s C: 
Please remove space and try again

Same problem after svelteesp32. and before h extension.

**Comment by playmiel** [comment]
still nothing, I changed my folders and the command: `npx svelteesp32 -e psychic -s dist -o 'C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\src\svelteesp32.h' 
--etag` and even with this command: `npx svelteesp32 -s 'C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\svelte\dist' -o 'C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\src\svelteesp32. h' --etag` it doesn't work in output I just have this `//engine: PsychicHttpServer
//cmdline: -e psychic -s dist -o C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\src\svelteesp32.h --etag
//created: 02/22/2024 16:10:58
//files: 0
//memory: 0


void initSvelteStaticFiles(PsychicHttpServer * server) {
}`

**Comment by BCsabaEngine** [comment]
So the command is ok, file generated but empty. I will try under windows (not I try linux and mac) soon.

**Comment by BCsabaEngine** [comment]
v1.2.1 available, please try it with same command line. After you try I need a feedback about URLs in the generated header file, these must to be linux path instead of windows path too.

**Comment by playmiel** [comment]
Thanks

Le jeu. 22 févr. 2024, 19:21, Csaba Balázs ***@***.***> a
écrit :

**Comment by BCsabaEngine** [comment]
Need a success/failed feedback to close issue. Please give one!

**Comment by playmiel** [comment]
however, I noticed that it doesn't add headers to .h files like 
```
#include <Arduino.h>.
#include <PsychicHttp.h>
#include <PsychicHttpsServer.h>
```

**Comment by BCsabaEngine** [comment]
> yes I can use the generated code everything works fine I just had to add the headers

https://github.com/BCsabaEngine/svelteesp32/issues/7

**Comment by playmiel** [comment]
Thanks after a little test it works well

Le ven. 23 févr. 2024, 22:49, Csaba Balázs ***@***.***> a
écrit :

**Comment by playmiel** [comment]
Hello, I can confirm that it works well with this command: 
`npx svelteesp32 -e psychic -s 'C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\svelte\dist' -o 'C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\src\svelteesp32.h' --etag --espmethod 'initSvelteStaticFile'`
 I have this as output:
 ```
//engine : PsychicHttpServer
//cmdline : -e psychic -s C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\svelte\dist -o C:\Users\Geko\Documents\PlatformIO\Projects\scenario_esp32_test\src\svelteesp32.h --etag --espmethod initSvelteStaticFile
//Created : 02/27/2024 17:16:36
//files : 5
//Memory: 145007

#include <Arduino.h>
#include <PsychicHttp.h>
#include <PsychicHttpsServer.h>
```

**Comment by BCsabaEngine** [comment]
Thank you very much foe your response.
